### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by juul-ka** [minvws/nl-covid19-notification-app-backend#30]
### Describe the bug, issue or concern

Docker local run fails

### To Reproduce
1. git clone repo
2. cd docker
3. docker-compose up --build
4. Errors in Dockerfile: due deletion of Components/Framework/WindowsIdentityStuff.cs on initial run
solved by using RUN rm -rf
issues with the destination of csproj files and new names given to projects (CotentApi & MobileAppApi), path should be prefixed with src/

Missing projects:
DbProvision/DbProvision.csproj 
DbFillExampleContent/DbFillExampleContent.csproj

Changed names of exe files in entrypoint in docker-compose.yml

### Expected behavior
instruction from readme to run the project in docker should work without errors

### Governance
- [ X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by skos001** [comment]
Thanks for opening this issue @juul-ka 🙂 And sincere apologies for the late response.

We've pushed a different approach for the Docker setup, which may render some of the suggested changes in your linked pull request unnecessary.

If you want, you can check to see if the current setup fixes your issue as well. If so, great! We can close the issue and corresponding pull request. If not, please feel free to either update this issue with any new findings, or open a new issue with any new findings if you prefer 😊

**Comment by skos001** [comment]
@juul-ka I'm going to go ahead and close this issue and its corresponding pull request since it's been a while since my last comment, and the code base has changed a bit since you opened the original issue. 😊

The Docker setup within the project should now work without issue on Windows, Linux and macOS (excepting macOS M1, which has specific work-around instructions in the README).

However, please feel free to open a new issue and pull request if you find something is still amiss with the Docker setup 🙂
